### ISSUE TITLE
makeglossarie script

### ISSUE THREAD

**Issue by TheoVerhelst** [RobinPetit/INFOF-209#1]
Tu pourrais inclure le script makeglossaries ?
Parce que la compilation marche moyen chez moi quand il s'agit de faire
```
    /home/poupou/texmf/scripts/glossaries/makeglossaries srd
```
:stuck_out_tongue:

**Comment by loan181** [comment]
Tu dois installer le package *glossaries* et utiliser le script en donnant le bon path (le mieux c'est de rajouter le path (un truc du genre /home/MaBiche/texmf/scripts/glossaries/) et puis de juste mettre `makeglossaries` dans le makefile

**Comment by loan181** [comment]
Oh le BATARD il a fermé :'( :-1: :-1000:

**Comment by TheoVerhelst** [comment]
T'es un grand sentimental Lolo
