### ISSUE TITLE
Activity1_Gameplay.png

### ISSUE THREAD

**Issue by areynoua** [RobinPetit/INFOF-209#2]
Dans le schéma on parle de “héro”. Kesako? (et en passant il faudrait peut-être un s).
Je sais pas comment on met un commentaire à un fichier sur github alors désolé si je fais pas ça où il faut.

**Comment by RobinPetit** [comment]
On ne sait pas commenter un binaire.

Je suppose que c'est le joueur, il faut que le créateur du schéma confirme ou démentisse. Ping @TheoVerhelst @kymogram (je ne sais pas lequel des deux l'a fait).

**Comment by TheoVerhelst** [comment]
Effectivement, il n'y a pas de mention de héros dans la consigne, je corrige.
